# Generated by Django 5.1.7 on 2025-06-21 11:35

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100, null=True)),
                ('student_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_father_first_name', models.CharField(max_length=100, null=True)),
                ('student_father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_father_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_mother_first_name', models.CharField(max_length=100, null=True)),
                ('student_mother_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_mother_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(max_length=100, null=True)),
                ('student_phone_number', models.CharField(max_length=15, null=True)),
                ('student_birth_date', models.DateField(null=True)),
                ('student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Trans Gender')], max_length=15)),
                ('student_id', models.CharField(max_length=10, null=True)),
                ('student_entry_year', models.CharField(max_length=100, null=True)),
                ('student_semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('fourth', 'Fourth Semester')], max_length=100)),
                ('student_address_line_1', models.CharField(max_length=100, null=True)),
                ('student_address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('student_city', models.CharField(max_length=100, null=True)),
                ('student_state', models.CharField(max_length=100, null=True)),
                ('student_zip', models.CharField(max_length=100, null=True)),
                ('student_image', models.ImageField(null=True, upload_to=student.models.student_image_upload_path)),
                ('guardian_address_line_1', models.CharField(max_length=100, null=True)),
                ('guardian_address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_city', models.CharField(max_length=100, null=True)),
                ('guardian_state', models.CharField(max_length=100, null=True)),
                ('guardian_zip', models.CharField(max_length=100, null=True)),
                ('first_emergency_first_name', models.CharField(max_length=100, null=True)),
                ('first_emergency_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_emergency_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_emergency_phone_number', models.CharField(max_length=100, null=True)),
                ('first_emergency_relationship', models.CharField(max_length=100, null=True)),
                ('second_emergency_first_name', models.CharField(max_length=100, null=True)),
                ('second_emergency_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_emergency_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_emergency_phone_number', models.CharField(max_length=100, null=True)),
                ('second_emergency_relationship', models.CharField(max_length=100, null=True)),
                ('physician_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_primary_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_secondary_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_special_notes', models.TextField(blank=True, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school_city', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school_state', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_school_date_started', models.DateField(blank=True, null=True)),
                ('previous_school_date_ended', models.DateField(blank=True, null=True)),
                ('previous_school_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
